# Read the Docs configuration file
# 官方文档：https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# 构建环境配置
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - echo "📚 正在构建 Trans-Hub 文档..."

# 使用 Sphinx 构建文档，配置文件路径如下
sphinx:
  configuration: docs/conf.py

# Python 环境配置
python:
  install:
    - method: pip
      requirements: docs/requirements.txt