# ==============================================================================
#  构建系统配置
# ==============================================================================
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


# ==============================================================================
#  项目元数据与依赖 (Poetry 配置) - v1.0.0 发布版
# ==============================================================================
[tool.poetry]
# --- 基本信息 ---
name = "trans-hub"
version = "1.0.0"
description = "一个可嵌入的、带持久化存储的智能本地化（i18n）后端引擎。"
authors = ["Saken <saken.w@gmail.com>"]
license = "MIT"
readme = "README.md"

# --- 链接信息 (会显示在 PyPI 页面) ---
homepage = "https://github.com/SakenW/trans-hub" # 替换为你的 GitHub 地址
repository = "https://github.com/SakenW/trans-hub" # 替换为你的 GitHub 地址
documentation = "https://github.com/SakenW/trans-hub/blob/main/README.md" # 链接到 README 或更详细的文档

# --- PyPI 分类器 (非常重要！) ---
# 帮助用户在 PyPI 上更好地发现和了解你的项目。
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Localization",
    "Topic :: Text Processing",
]

# --- 核心依赖 (项目的最小运行集) ---
# 这些是用户运行 `pip install trans-hub` 时会安装的包。
[tool.poetry.dependencies]
python = "^3.9"

pydantic = "^2.0"
structlog = "^23.0"


# --- 可选依赖 (Extras) ---
# 这使得用户可以按需安装功能，例如 `pip install "trans-hub[openai]"`。
[tool.poetry.extras]
# 定义一个名为 'openai' 的功能集。
openai = ["openai", "pydantic-settings", "python-dotenv"]

# 未来可以增加其他引擎
# deepl = ["deepl"]
# google = ["google-cloud-translate"]

# 定义一个名为 'all' 的特殊功能集，它包含了所有可选功能。
# all = ["openai", "pydantic-settings", "python-dotenv", "deepl"]


# --- 开发依赖 (仅在开发和测试时需要) ---
# 通过 `poetry install --with dev` 安装。
[tool.poetry.group.dev.dependencies]
# 测试框架
pytest = "^7.4"
pytest-cov = "^4.1"
pytest-asyncio = "^0.21.0" # 用于未来测试异步代码

# 代码风格与检查
black = "^23.0"
isort = "^5.12"
ruff = "^0.1.0"
mypy = "^1.5"

# [重要] 开发时，我们也需要安装所有可选依赖，以确保能运行所有测试。
# 这是最直接的方式，确保 `poetry install --with dev` 能安装所有东西。
openai = "^1.37.0"
pydantic-settings = "^2.3.4"
python-dotenv = "^1.0.1"


# ==============================================================================
#  开发工具配置
# ==============================================================================

[tool.black]
line-length = 88
target-version = ['py39']

[tool.isort]
profile = "black"
line_length = 88

[tool.ruff]
line-length = 88
select = ["E", "W", "F", "I", "N", "D", "UP", "B", "C4"]
ignore = ["D100", "D104", "D107"]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true