[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "trans-hub"
version = "1.0.0"
description = "一个可嵌入的、带持久化存储的智能本地化（i18n）后端引擎。"
authors = ["Saken <saken.w@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/SakenW/trans-hub"
repository = "https://github.com/SakenW/trans-hub"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Localization",
]

# --- 核心依赖 (项目的最小运行集) ---
[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.0"
structlog = "^23.0"

# --- 可选依赖 (Extras) ---
[tool.poetry.extras]
# 定义一个名为 'openai' 的功能集。
openai = ["openai", "pydantic-settings", "python-dotenv"]
# 未来可以增加其他引擎
# deepl = ["deepl"]

# --- 开发依赖 (仅在开发和测试时需要) ---
[tool.poetry.group.dev.dependencies]
pytest = "^7.4"
pytest-cov = "^4.1"
pytest-asyncio = "^0.21.0"
black = "^23.0"
isort = "^5.12"
ruff = "^0.1.0"
mypy = "^1.5"

# 开发时，我们直接在这里列出所有可选依赖，以确保测试能覆盖所有功能
openai = "^1.37.0"
pydantic-settings = "^2.3.4"
python-dotenv = "^1.0.1"