# 忽略特定错误
# 设置最大行长度
line-length = 88

# 排除的目录
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "docs",
    "examples",
    "tests",
    "tools",
]

[lint]
# 忽略的规则
ignore = [
    "E402",  # 忽略模块级导入不在文件顶部的错误
    "B904",  # 忽略异常处理中的raise问题
    "B008",  # 忽略函数调用作为参数默认值的问题
]

# 启用的规则集
select = [
    "E",  # 错误
    "F",  # 致命错误
    "W",  # 警告
    "B",  # 布尔克规则
    "I",  # 导入规则
]