# packages/core/pyproject.toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "trans-hub-core"
version = "0.1.0"
description = "Trans-Hub 核心契约包，定义了接口、类型和异常。"
authors = ["SakenW <saken.w@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10"
pydantic = "^2.0"
langcodes = ">=3.3.0" # [新增] 白皮书要求，用于BCP-47校验