# packages/server/pyproject.toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "trans-hub-server"
version = "0.1.0"
description = "Trans-Hub 服务端实现，包含应用、基础设施和表现层。"
authors = ["Saken <saken.w@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "trans_hub", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"

# --- 核心依赖 ---
pydantic = ">=2.9.2,<3.0.0"            # 最新稳定版 2.9.x（2025 年 8 月）
pydantic-settings = ">=2.6.0,<3.0.0"   # 最新 2.x 系列
structlog = ">=24.4.0,<25.0.0"         # 最新 2025 版本

# --- 引用本地的 core 和 uida 包 ---
trans-hub-core = { path = "../core", develop = true }
trans-hub-uida = { path = "../uida", develop = true }

# --- 数据库核心 ---
sqlalchemy = { version = ">=2.0.43,<3.0.0", extras = ["asyncio"] }  # 最新稳定版
alembic    = ">=1.16.4,<2.0.0"                                     # 最新稳定版
greenlet   = ">=3.0.3,<4.0.0"                                      # Alembic 需要

# --- 可选驱动与库 (通过 extras 安装) ---
asyncpg   = { version = ">=0.29.0", optional = true }
aiosqlite = { version = ">=0.19.0", optional = true }
redis     = { version = ">=5.0.0", extras = ["hiredis"], optional = true }
typer     = { version = ">=0.12.5,<0.13.0", extras = ["all"], optional = true } # 最新稳定版
textual   = { version = ">=5.3.0,<6.0.0", optional = true }  # 最新稳定版

[tool.poetry.extras]
postgres = ["asyncpg"]
sqlite   = ["aiosqlite"]
redis    = ["redis"]
# [关键修复] 将 textual 添加回 cli extras 组
cli      = ["typer", "textual"]

# --- 开发与测试依赖 ---
[tool.poetry.group.dev.dependencies]
pytest         = ">=8.3.2,<9.0.0"       # 最新稳定版
pytest-asyncio = ">=0.23.8,<0.24.0"     # 最新稳定版
pytest-cov     = ">=5.0.0,<6.0.0"       # 最新稳定版
ruff           = ">=0.6.9,<0.7.0"       # 最新稳定版
mypy           = ">=1.11.1,<2.0.0"      # 最新稳定版
rich           = ">=13.9.2,<14.0.0"     # 最新稳定版
questionary    = ">=2.0.1,<3.0.0"
psycopg        = { version = ">=3.2.3,<4.0.0", extras = ["binary"] }  # 最新稳定版

[tool.poetry.scripts]
trans-hub = "trans_hub.presentation.cli.main:app"

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = [".", "src", "tests"]